# Generated by Django 6.0.1 on 2026-01-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('colors', models.JSONField(blank=True, null=True)),
                ('memory_capacity', models.JSONField(blank=True, null=True)),
                ('manufacturer', models.CharField(max_length=255, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('promotional_price', models.CharField(max_length=100, null=True)),
                ('product_code', models.CharField(max_length=255, null=True, unique=True)),
                ('number_of_reviews', models.CharField(max_length=255, null=True)),
                ('screen_diagonal', models.CharField(max_length=255, null=True)),
                ('display_resolution', models.CharField(max_length=50, null=True)),
                ('characteristics', models.JSONField(blank=True, null=True)),
                ('photos', models.JSONField(blank=True, help_text='Ссылки на все фото товара', null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(default='New', max_length=50, null=True)),
            ],
        ),
    ]
